CREATE TABLE IF NOT EXISTS archives (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR UNIQUE,
  path VARCHAR,
  syncDate Date
);

CREATE TABLE IF NOT EXISTS audios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR,
  path VARCHAR,
  playbackTime INTEGER,
  archiveId INTEGER,
  albumId INTEGER,
  albumOrder INTEGER,
  FOREIGN KEY(archiveId) REFERENCES archives(id)
);
